name: Run mvn test & Test coverage upload to Codecov & Deep Source analyze & Sonar analyzer

on:
  push:
    branches: [main, dev, feature/* ]
  pull_request:
    branches: [main, dev, feature/* ]

jobs:
  all:
    runs-on: ubuntu-latest

    steps:
      - name: Pull project
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run mvn test
        run: mvn --batch-mode --update-snapshots test

      - name: Report test coverage report on Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml

      - name: Sonarqube build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          echo "Running sonar scan on ${GITHUB_REF##refs/heads/} repo branch"
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Nouuu_AL-TradeMe -Dsonar.branch.name=${GITHUB_REF##refs/heads/}